#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1365563805.800263
__CHEETAH_genTimestamp__ = 'Wed Apr 10 00:16:45 2013'
__CHEETAH_src__ = '../model/MyWizard_cpp.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Apr  9 22:50:29 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class MyWizard_cpp(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(MyWizard_cpp, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
#include "wx/imaglist.h"
////@end includes

#include "''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 12, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 12, col 12.
        write(u'''.h"

////@begin XPM images
////@end XPM images

/*
 * ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 18, col 4
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 18, col 4.
        write(u''' type definition
 */

IMPLEMENT_DYNAMIC_CLASS(''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 21, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 21, col 25.
        write(u''', wxWizard)

/*
 * ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 24, col 4
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 24, col 4.
        write(u''' event table definition
 */

BEGIN_EVENT_TABLE(''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 27, col 19
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 27, col 19.
        write(u''', wxWizard)

////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 29, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 29, col 12.
        write(u''' event table entries
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 30, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 30, col 10.
        write(u''' event table entries

END_EVENT_TABLE()

/*
 * ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 35, col 4
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 35, col 4.
        write(u''' constructors
 */

''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 38, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 38, col 1.
        write(u'''::''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 38, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 38, col 16.
        write(u'''()
{
\tInit();
}

''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 43, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 43, col 1.
        write(u'''::''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 43, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 43, col 16.
        write(u'''(wxWindow *parent, wxWindowID id, const wxPoint &pos)
{
\tInit();
\tCreate(parent, id, pos);
}

/*
 * ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 50, col 4
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 50, col 4.
        write(u''' creator
 */

bool ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 53, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 53, col 6.
        write(u'''::Create(wxWindow *parent, wxWindowID id, const wxPoint &pos)
{
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 55, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 55, col 12.
        write(u''' creation
\tSetExtraStyle(wxWS_EX_BLOCK_EVENTS | wxWIZARD_EX_HELPBUTTON);
\tSetParent(parent);
\tCreateControls();
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 59, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 59, col 10.
        write(u''' creation
\treturn true;
}

/*
 * ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 64, col 4
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 64, col 4.
        write(u''' destructor
 */

''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 67, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 67, col 1.
        write(u'''::~''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 67, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 67, col 17.
        write(u'''()
{
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 69, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 69, col 12.
        write(u''' destruction
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 70, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 70, col 10.
        write(u''' destruction
}

/*
 * Member initialisation
 */

void ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 77, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 77, col 6.
        write(u'''::Init()
{
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 79, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 79, col 12.
        write(u''' member initialisation
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 80, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 80, col 10.
        write(u''' member initialisation
}

/*
 * Control creation for ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 84, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 84, col 25.
        write(u'''
 */

void ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 87, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 87, col 6.
        write(u'''::CreateControls()
{
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 89, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 89, col 12.
        write(u''' content construction

\tbool isLoadWizard =
\t\t\twxXmlResource::Get()->LoadObject(
\t\t\t\t\tthis,
\t\t\t\t\tGetParent(),
\t\t\t\t\t_T("ID_''')
        _v = VFFSL(SL,"class_name_upper",True) # u'${class_name_upper}' on line 95, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name_upper}')) # from line 95, col 13.
        write(u'''"),
\t\t\t\t\twxT("wxWizard")
\t\t\t);

\tif (!isLoadWizard) {
\t\twxLogError(wxT("Missing wxXmlResource::Get()->Load() in OnInit()?"));
\t}

\tfor (wxWindowList::Node *node = GetChildren().GetFirst(); node; node = node->GetNext())
\t{

\t\twxWizardPage *page = wxDynamicCast(node->GetData(), wxWizardPage);

\t\tif (page)
\t\t{
\t\t\tGetPageAreaSizer()->Add(page);
\t\t}

\t}

////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 115, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 115, col 10.
        write(u''' content construction

\t// Create custom windows not generated automatically here.
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 118, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 118, col 12.
        write(u''' content initialisation
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 119, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 119, col 10.
        write(u''' content initialisation
}

/*
 * Runs the wizard.
 */

bool ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 126, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 126, col 6.
        write(u'''::Run()
{
\twxWindowList::compatibility_iterator node = GetChildren().GetFirst();

\twhile (node) {
\t\twxWizardPage *startPage = wxDynamicCast(node->GetData(), wxWizardPage);

\t\tif (startPage) {
\t\t\treturn RunWizard(startPage);
\t\t}

\t\tnode = node->GetNext();
\t}

\treturn false;
}

/*
 * Should we show tooltips?
 */

bool ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 147, col 6
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 147, col 6.
        write(u'''::ShowToolTips()
{
\treturn true;
}

/*
 * Get bitmap resources
 */

wxBitmap ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 156, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 156, col 10.
        write(u'''::GetBitmapResource(const wxString &name)
{
\t// Bitmap retrieval
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 159, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 159, col 12.
        write(u''' bitmap retrieval
\twxUnusedVar(name);
\treturn wxNullBitmap;
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 162, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 162, col 10.
        write(u''' bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 169, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 169, col 8.
        write(u'''::GetIconResource(const wxString &name)
{
\t// Icon retrieval
////@begin ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 172, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 172, col 12.
        write(u''' icon retrieval
\twxUnusedVar(name);
\treturn wxNullIcon;
////@end ''')
        _v = VFFSL(SL,"class_name",True) # u'${class_name}' on line 175, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${class_name}')) # from line 175, col 10.
        write(u''' icon retrieval
}
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_MyWizard_cpp= 'respond'

## END CLASS DEFINITION

if not hasattr(MyWizard_cpp, '_initCheetahAttributes'):
    templateAPIClass = getattr(MyWizard_cpp, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(MyWizard_cpp)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=MyWizard_cpp()).run()


