#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1448321211.24696
__CHEETAH_genTimestamp__ = 'Mon Nov 23 21:26:51 2015'
__CHEETAH_src__ = 'model/AdtHeader_h.tmpl'
__CHEETAH_srcLastModified__ = 'Sat Nov 21 03:56:25 2015'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class AdtHeader_h(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(AdtHeader_h, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''#ifndef ''')
        _v = VFFSL(SL,"header_name_without_h_uppercase",True) # u'${header_name_without_h_uppercase}' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${header_name_without_h_uppercase}')) # from line 1, col 10.
        write(u'''_H
#define ''')
        _v = VFFSL(SL,"header_name_without_h_uppercase",True) # u'${header_name_without_h_uppercase}' on line 2, col 10
        if _v is not None: write(_filter(_v, rawExpr=u'${header_name_without_h_uppercase}')) # from line 2, col 10.
        write(u'''_H

/*****************************************************************************
 *                                                                           *
 * ---------------------------- Public Interface --------------------------- *
 *                                                                           *
 *****************************************************************************/

/*
A pointer to an incomplete type (hides the implementation details).
*/
typedef struct ''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 13, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 13, col 16.
        write(u'''* ''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 13, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 13, col 32.
        write(u'''Ptr;

''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 15, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 15, col 1.
        write(u'''Ptr create''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 15, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 15, col 25.
        write(u'''(''')
        _v = VFFSL(SL,"Arguments",True) # u'${Arguments}' on line 15, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${Arguments}')) # from line 15, col 40.
        write(u''');

void destroy''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 17, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 17, col 13.
        write(u'''(''')
        _v = VFFSL(SL,"struct_name",True) # u'${struct_name}' on line 17, col 28
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name}')) # from line 17, col 28.
        write(u'''Ptr ''')
        _v = VFN(VFFSL(SL,"struct_name",True),"lower",False)() # u'${struct_name.lower()}' on line 17, col 46
        if _v is not None: write(_filter(_v, rawExpr=u'${struct_name.lower()}')) # from line 17, col 46.
        write(u''');

#endif       /* ''')
        _v = VFFSL(SL,"header_name_without_h_uppercase",True) # u'${header_name_without_h_uppercase}' on line 19, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${header_name_without_h_uppercase}')) # from line 19, col 17.
        write(u'''_H */
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_AdtHeader_h= 'respond'

## END CLASS DEFINITION

if not hasattr(AdtHeader_h, '_initCheetahAttributes'):
    templateAPIClass = getattr(AdtHeader_h, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(AdtHeader_h)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=AdtHeader_h()).run()


