#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1366354185.917224
__CHEETAH_genTimestamp__ = 'Fri Apr 19 03:49:45 2013'
__CHEETAH_src__ = '../model/AbstractFactory_java.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Apr 19 03:49:42 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class AbstractFactory_java(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(AbstractFactory_java, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''public abstract class ''')
        _v = VFFSL(SL,"AbstractFactory",True) # u'${AbstractFactory}' on line 1, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'${AbstractFactory}')) # from line 1, col 23.
        write(u''' {
\tpublic static ''')
        _v = VFFSL(SL,"AbstractFactory",True) # u'${AbstractFactory}' on line 2, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${AbstractFactory}')) # from line 2, col 16.
        write(u''' ''')
        _v = VFFSL(SL,"Get",True) # u'${Get}' on line 2, col 35
        if _v is not None: write(_filter(_v, rawExpr=u'${Get}')) # from line 2, col 35.
        write(u'''(''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 2, col 42
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 2, col 42.
        write(u''' ''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 2, col 52
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 2, col 52.
        write(u'''Type)
\t{
''')
        if len(VFFSL(SL,"ConcreteFactory",True)) == 1: # generated from line 4, col 3
            write(u'''\t\treturn new ''')
            _v = VFFSL(SL,"ConcreteFactory",True)[0] # u'${ConcreteFactory[0]}' on line 5, col 14
            if _v is not None: write(_filter(_v, rawExpr=u'${ConcreteFactory[0]}')) # from line 5, col 14.
            write(u'''();
''')
        else: # generated from line 6, col 3
            write(u'''

\t\tif (''')
            _v = VFFSL(SL,"Family",True) # u'${Family}' on line 9, col 7
            if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 9, col 7.
            write(u'''Type == ''')
            _v = VFFSL(SL,"Family",True) # u'${Family}' on line 9, col 24
            if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 9, col 24.
            write(u'''.''')
            _v = VFFSL(SL,"FamilyTypes",True)[0] # u'${FamilyTypes[0]}' on line 9, col 34
            if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[0]}')) # from line 9, col 34.
            write(u''') {
\t\t\treturn new ''')
            _v = VFFSL(SL,"ConcreteFactory",True)[0] # u'${ConcreteFactory[0]}' on line 10, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'${ConcreteFactory[0]}')) # from line 10, col 15.
            write(u'''();
\t\t}
\t\t
''')
            for x in range(1, len(VFFSL(SL,"FamilyTypes",True))-1): # generated from line 13, col 3
                write(u'''\t\telse if (''')
                _v = VFFSL(SL,"Family",True) # u'${Family}' on line 14, col 12
                if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 14, col 12.
                write(u'''Type == ''')
                _v = VFFSL(SL,"Family",True) # u'${Family}' on line 14, col 29
                if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 14, col 29.
                write(u'''.''')
                _v = VFFSL(SL,"FamilyTypes",True)[x] # u'${FamilyTypes[x]}' on line 14, col 39
                if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[x]}')) # from line 14, col 39.
                write(u''') {
\t\t\treturn new ''')
                _v = VFFSL(SL,"ConcreteFactory",True)[x] # u'${ConcreteFactory[x]}' on line 15, col 15
                if _v is not None: write(_filter(_v, rawExpr=u'${ConcreteFactory[x]}')) # from line 15, col 15.
                write(u'''();
\t\t}
''')
            write(u'''
\t\telse {
\t\t\t// ''')
            _v = VFFSL(SL,"FamilyTypes",True)[-1] # u'${FamilyTypes[-1]}' on line 20, col 7
            if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[-1]}')) # from line 20, col 7.
            write(u'''
\t\t\treturn new ''')
            _v = VFFSL(SL,"ConcreteFactory",True)[-1] # u'${ConcreteFactory[-1]}' on line 21, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'${ConcreteFactory[-1]}')) # from line 21, col 15.
            write(u'''();
\t\t}
''')
        write(u'''\t}

''')
        for x in range(0, len(VFFSL(SL,"AbstractMethod",True))): # generated from line 26, col 2
            write(u'''\tpublic abstract ''')
            _v = VFFSL(SL,"AbstractProduct",True)[x] # u'${AbstractProduct[x]}' on line 27, col 18
            if _v is not None: write(_filter(_v, rawExpr=u'${AbstractProduct[x]}')) # from line 27, col 18.
            write(u''' ''')
            _v = VFFSL(SL,"AbstractMethod",True)[x] # u'${AbstractMethod[x]}' on line 27, col 40
            if _v is not None: write(_filter(_v, rawExpr=u'${AbstractMethod[x]}')) # from line 27, col 40.
            write(u'''();
''')
        write(u'''}

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_AbstractFactory_java= 'respond'

## END CLASS DEFINITION

if not hasattr(AbstractFactory_java, '_initCheetahAttributes'):
    templateAPIClass = getattr(AbstractFactory_java, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(AbstractFactory_java)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=AbstractFactory_java()).run()


