#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1366352555.055393
__CHEETAH_genTimestamp__ = 'Fri Apr 19 03:22:35 2013'
__CHEETAH_src__ = '../model/build_haml.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr 10 19:51:47 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class build_haml(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(build_haml, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''!!! XML
/
  Document   : build.haml -> build.xml
  Created on : #{Time.new}
  Author     : ivan
  Description:
  Purpose of the document follows.

/
  Projeto
%project{:basedir => ".", :default => "dist", :name => "AbstractFactory"}

  /
    Remove end spaces
  %target{ :name => "remove-trailing-spaces" }
    %echo
      Remove Trailing Spaces.
    %apply{ :executable  => "sed",
            :failonerror => "true" }
      %arg{ :value => "s/[ ]*$//" }/
      %arg{ :value => "-i" }/
      %fileset{ :dir => "src" }
        %include{ :name => "**/*.java" }/
  /
    Squeeze with SED.
  %target{ :name    => "squeeze-blank",
           :depends => "remove-trailing-spaces" }
    %echo
      Suppress repeated empty output lines.
    %apply{ :executable  => "sed",
            :failonerror => "true" }
      %arg{ :value => "/^$/N;/\\\\n$/D" }/
      %arg{ :value => "-i" }/
      %fileset{ :dir => "src" }
        %include{ :name => "**/*.java" }/
  /
    Artistic Style 1.24
    Maintained by: Jim Pattee
    Original Author: Tal Davidson
  %target{ :name    => "indent",
           :depends => "squeeze-blank" }
    %echo
      Indenting source code.
    %apply{:executable  => "astyle",
           :failonerror => "true" }
      %arg{:value => "-A4" }/
      %arg{:value => "-s4" }/
      %arg{:value => "--indent=spaces=4" }/
      %arg{:value => "-t4" }/
      %arg{:value => "-b"  }/
      %arg{:value => "-S"  }/
      %arg{:value => "-N"  }/
      %arg{:value => "-L"  }/
      %arg{:value => "-w"  }/
      %arg{:value => "-U"  }/
      %arg{:value => "-F"  }/
      %arg{:value => "-p"  }/
      %arg{:value => "-H"  }/
      %arg{:value => "-j"  }/
      %arg{:value => "-y"  }/
      %arg{:value => "-k3" }/
      %arg{:value => "-z2" }/
      %fileset{:dir => "src" }
        %include{:name => "**/*.java" }/

  %property{:name => "src.dir",     :value => "src"}/
  %property{:name => "build.dir",   :value => "build"}/
  %property{:name => "dist.dir",    :value => "dist"}/
  %property{:name => "classes.dir", :value => "${build.dir}/classes"}/
  %property{:name => "jar.dir",     :value => "${dist.dir}/lib"}/
  %property{:name => "main-class",  :value => "${main}"}/

  %description
    simple example build file

  %target{:name => "init"}

    /
      Create the time stamp
    %tstamp/

    /
      Create the build directory structure used by compile
    %mkdir{:dir => "${classes.dir}"}/

  %target{:depends     => "init",
          :description => "compile the source ",
          :name        => "compile"}

    /
      Compile the java code from ${src} into ${build}
    %javac{:destdir           => "${classes.dir}",
           :includeantruntime => "false",
           :srcdir            => "${src.dir}"}/

  %target{:depends           => "compile",
          :description       => "generate the distribution",
          :name              => "dist"}

    /
      Create the distribution directory
    %mkdir{:dir => "${jar.dir}"}/

    /
      Put everything in ${build} into the MyProject-${DSTAMP}.jar file
    %jar{:basedir  => "${classes.dir}",
         :destfile => "${jar.dir}/${ant.project.name}.jar"}
      %manifest
        %attribute{:name  => "Main-Class",
                   :value => "${main-class}"}/

  %target{:name        => "run",
          :description => "run the aplication" }
    %java{:jar  => "${jar.dir}/${ant.project.name}.jar",
          :fork => "true" }/

  %target{:description => "clean up",
          :name        => "clean"}

    /
      Delete the ${build} and ${dist} directory trees
    %delete{:dir => "${build.dir}"}/
    %delete{:dir => "${dist.dir}" }/

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_build_haml= 'respond'

## END CLASS DEFINITION

if not hasattr(build_haml, '_initCheetahAttributes'):
    templateAPIClass = getattr(build_haml, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(build_haml)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=build_haml()).run()


