#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1366352554.16401
__CHEETAH_genTimestamp__ = 'Fri Apr 19 03:22:34 2013'
__CHEETAH_src__ = '../model/Client_java.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Apr 14 16:36:21 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Client_java(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(Client_java, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''public class ''')
        _v = VFFSL(SL,"Client",True) # u'${Client}' on line 1, col 14
        if _v is not None: write(_filter(_v, rawExpr=u'${Client}')) # from line 1, col 14.
        write(u''' {
\tpublic static void main(String[] args)
\t{

''')
        for x in range(0, len(VFFSL(SL,"FamilyTypes",True))): # generated from line 5, col 3
            write(u'''\t\t//''')
            _v = VFFSL(SL,"Family",True) # u'${Family}' on line 6, col 5
            if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 6, col 5.
            write(u''' ''')
            _v = VFFSL(SL,"Family",True) # u'${Family}' on line 6, col 15
            if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 6, col 15.
            write(u'''Type = ''')
            _v = VFFSL(SL,"Family",True) # u'${Family}' on line 6, col 31
            if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 6, col 31.
            write(u'''.''')
            _v = VFFSL(SL,"FamilyTypes",True)[x] # u'${FamilyTypes[x]}' on line 6, col 41
            if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[x]}')) # from line 6, col 41.
            write(u''';
''')
        write(u'''\t\t''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 8, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 8, col 3.
        write(u''' ''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 8, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 8, col 13.
        write(u'''Type = ''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 8, col 29
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 8, col 29.
        write(u'''.''')
        _v = VFFSL(SL,"FamilyTypes",True)[0] # u'${FamilyTypes[0]}' on line 8, col 39
        if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[0]}')) # from line 8, col 39.
        write(u''';

\t\t''')
        _v = VFFSL(SL,"AbstractFactory",True) # u'${AbstractFactory}' on line 10, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${AbstractFactory}')) # from line 10, col 3.
        write(u''' factory = ''')
        _v = VFFSL(SL,"AbstractFactory",True) # u'${AbstractFactory}' on line 10, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'${AbstractFactory}')) # from line 10, col 32.
        write(u'''.''')
        _v = VFFSL(SL,"Get",True) # u'${Get}' on line 10, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'${Get}')) # from line 10, col 51.
        write(u'''(''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 10, col 58
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 10, col 58.
        write(u'''Type);

''')
        for x in range(0, len(VFFSL(SL,"AbstractProduct",True))): # generated from line 12, col 3
            write(u'''\t\t''')
            _v = VFFSL(SL,"AbstractProduct",True)[x] # u'${AbstractProduct[x]}' on line 13, col 3
            if _v is not None: write(_filter(_v, rawExpr=u'${AbstractProduct[x]}')) # from line 13, col 3.
            write(u''' obj_''')
            _v = VFFSL(SL,"x",True) # u'${x}' on line 13, col 29
            if _v is not None: write(_filter(_v, rawExpr=u'${x}')) # from line 13, col 29.
            write(u''' = factory.''')
            _v = VFFSL(SL,"AbstractMethod",True)[x] # u'${AbstractMethod[x]}' on line 13, col 44
            if _v is not None: write(_filter(_v, rawExpr=u'${AbstractMethod[x]}')) # from line 13, col 44.
            write(u'''();
\t\tobj_''')
            _v = VFFSL(SL,"x",True) # u'${x}' on line 14, col 7
            if _v is not None: write(_filter(_v, rawExpr=u'${x}')) # from line 14, col 7.
            write(u'''.''')
            _v = VFFSL(SL,"doIt",True)[x] # u'${doIt[x]}' on line 14, col 12
            if _v is not None: write(_filter(_v, rawExpr=u'${doIt[x]}')) # from line 14, col 12.
            write(u'''();

''')
        write(u'''\t}

}
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_Client_java= 'respond'

## END CLASS DEFINITION

if not hasattr(Client_java, '_initCheetahAttributes'):
    templateAPIClass = getattr(Client_java, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Client_java)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Client_java()).run()


