#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1366352554.729854
__CHEETAH_genTimestamp__ = 'Fri Apr 19 03:22:34 2013'
__CHEETAH_src__ = '../model/Family_java.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Apr 14 16:36:30 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Family_java(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(Family_java, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''public enum ''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 1, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 1, col 13.
        write(u''' {

''')
        for x in range(0, len(VFFSL(SL,"FamilyTypes",True))): # generated from line 3, col 2
            if x == len(VFFSL(SL,"FamilyTypes",True))-1: # generated from line 4, col 2
                write(u'''\t''')
                _v = VFFSL(SL,"FamilyTypes",True)[x] # u'${FamilyTypes[x]}' on line 5, col 2
                if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[x]}')) # from line 5, col 2.
                write(u'''(''')
                _v = VFFSL(SL,"x",True) # u'${x}' on line 5, col 20
                if _v is not None: write(_filter(_v, rawExpr=u'${x}')) # from line 5, col 20.
                write(u''');
''')
            else: # generated from line 6, col 2
                write(u'''\t''')
                _v = VFFSL(SL,"FamilyTypes",True)[x] # u'${FamilyTypes[x]}' on line 7, col 2
                if _v is not None: write(_filter(_v, rawExpr=u'${FamilyTypes[x]}')) # from line 7, col 2.
                write(u'''(''')
                _v = VFFSL(SL,"x",True) # u'${x}' on line 7, col 20
                if _v is not None: write(_filter(_v, rawExpr=u'${x}')) # from line 7, col 20.
                write(u'''),
''')
        write(u'''
\tprivate final int ''')
        _v = VFFSL(SL,"family",True) # u'${family}' on line 11, col 20
        if _v is not None: write(_filter(_v, rawExpr=u'${family}')) # from line 11, col 20.
        write(u'''Type;

\t''')
        _v = VFFSL(SL,"Family",True) # u'${Family}' on line 13, col 2
        if _v is not None: write(_filter(_v, rawExpr=u'${Family}')) # from line 13, col 2.
        write(u'''(int ''')
        _v = VFFSL(SL,"family",True) # u'${family}' on line 13, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'${family}')) # from line 13, col 16.
        write(u'''Type)
\t{
\t\tthis.''')
        _v = VFFSL(SL,"family",True) # u'${family}' on line 15, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${family}')) # from line 15, col 8.
        write(u'''Type = ''')
        _v = VFFSL(SL,"family",True) # u'${family}' on line 15, col 24
        if _v is not None: write(_filter(_v, rawExpr=u'${family}')) # from line 15, col 24.
        write(u'''Type;
\t}

}
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_Family_java= 'respond'

## END CLASS DEFINITION

if not hasattr(Family_java, '_initCheetahAttributes'):
    templateAPIClass = getattr(Family_java, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Family_java)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Family_java()).run()


