#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1490984419.80336
__CHEETAH_genTimestamp__ = 'Fri Mar 31 15:20:19 2017'
__CHEETAH_src__ = '../m/client.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Mar 30 23:52:18 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class client(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(client, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''log_level    :''')
        _v = VFFSL(SL,"log.level",True) # u'${log.level}' on line 1, col 15
        if _v is not None: write(_filter(_v, rawExpr=u'${log.level}')) # from line 1, col 15.
        write(u'''
log_location ''')
        _v = VFFSL(SL,"log.location",True) # u'${log.location}' on line 2, col 14
        if _v is not None: write(_filter(_v, rawExpr=u'${log.location}')) # from line 2, col 14.
        write(u"""

chef_server_url        'https://""")
        _v = VFFSL(SL,"chef.url",True) # u'${chef.url}' on line 4, col 33
        if _v is not None: write(_filter(_v, rawExpr=u'${chef.url}')) # from line 4, col 33.
        write(u''':''')
        _v = VFFSL(SL,"chef.port",True) # u'${chef.port}' on line 4, col 45
        if _v is not None: write(_filter(_v, rawExpr=u'${chef.port}')) # from line 4, col 45.
        write(u"""'
validation_client_name '""")
        _v = VFFSL(SL,"validation.client_name",True) # u'${validation.client_name}' on line 5, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${validation.client_name}')) # from line 5, col 25.
        write(u"""'
validation_key         '""")
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 6, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 6, col 25.
        write(u'''/''')
        _v = VFFSL(SL,"validation.client_name",True) # u'${validation.client_name}' on line 6, col 32
        if _v is not None: write(_filter(_v, rawExpr=u'${validation.client_name}')) # from line 6, col 32.
        write(u""".pem'
node_name              '""")
        _v = VFFSL(SL,"chef.node_name",True) # u'${chef.node_name}' on line 7, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'${chef.node_name}')) # from line 7, col 25.
        write(u"""'

""")
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_client= 'respond'

## END CLASS DEFINITION

if not hasattr(client, '_initCheetahAttributes'):
    templateAPIClass = getattr(client, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(client)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=client()).run()


