#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1490984419.631733
__CHEETAH_genTimestamp__ = 'Fri Mar 31 15:20:19 2017'
__CHEETAH_src__ = '../m/dockerfile.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Mar 31 12:48:25 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class dockerfile(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(dockerfile, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''FROM chef_solo:latest
MAINTAINER ''')
        write(_filter( os.popen("git config --get user.name").read().strip()))
        write(u''' <''')
        write(_filter( os.popen("git config --get user.email").read().strip()))
        write(u'''>

# chef-solo
# ---------

RUN mkdir -p\\
  ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 8, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 8, col 3.
        write(u''' \\
  /root/.chef \\
  /root/.chef/syntax_check_cache \\
  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 11, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 11, col 3.
        write(u'''/roles        \\
  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 12, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 12, col 3.
        write(u'''/checksums    \\
  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 13, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 13, col 3.
        write(u'''/environments \\
  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 14, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 14, col 3.
        write(u'''/backup       \\
  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 15, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 15, col 3.
        write(u'''/cache

# add nodes
ADD src/nodes/node.json  ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 18, col 26
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 18, col 26.
        write(u'''/node.json

# add roles
ADD src/roles/superuser.json ''')
        _v = VFFSL(SL,"var",True) # u'${var}' on line 21, col 30
        if _v is not None: write(_filter(_v, rawExpr=u'${var}')) # from line 21, col 30.
        write(u'''/roles/superuser.json

# Add latest default chef-solo config files
ADD src/client.rb                      ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 24, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 24, col 40.
        write(u'''/client.rb
ADD src/solo.rb                        ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 25, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 25, col 40.
        write(u'''/solo.rb
ADD src/knife.rb                       /root/.chef/knife.rb
ADD src/pem/admin.pem                  ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 27, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 27, col 40.
        write(u'''/admin.pem
ADD src/pem/chef-validator.pem         ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 28, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 28, col 40.
        write(u'''/chef-validator.pem
ADD src/keys/encrypted_data_bag_secret ''')
        _v = VFFSL(SL,"etc",True) # u'${etc}' on line 29, col 40
        if _v is not None: write(_filter(_v, rawExpr=u'${etc}')) # from line 29, col 40.
        write(u'''/encrypted_data_bag_secret

ADD src/chef-initialize.sh /usr/local/bin/chef-initialize.sh
RUN chmod +x               /usr/local/bin/chef-initialize.sh

# copy supervisor conf
ADD src/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_dockerfile= 'respond'

## END CLASS DEFINITION

if not hasattr(dockerfile, '_initCheetahAttributes'):
    templateAPIClass = getattr(dockerfile, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(dockerfile)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=dockerfile()).run()


